# Numpy

In [3]:
import numpy as np

# Array creation and Properties

In [8]:
a= np.arange(10)  #prfix range() with "a" as arange
b =np.arange(20)

In [9]:
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [14]:
a= np.arange(12).reshape(3,4) #reshape(rows,columns)
print(a)
print(type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<class 'numpy.ndarray'>


# Numpy array has many meta data associated with its describing its shape.

In [17]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize) #each array element size 8bytes


2
(3, 4)
12
int64
8


In [20]:
d = np.array([1.0,4.0,8.0,7.0,5.0])
print(d)
print(d.dtype)
print(type(d))

[1. 4. 8. 7. 5.]
float64
<class 'numpy.ndarray'>


In [22]:
c=np.eye(9)
dtype = np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [6]:
d=np.linspace(-1,2,15,endpoint=True) #linspace(start ,end , no :values to be present ,endspace-"tells if you want the last point give it as two")
print(d)


[-1.         -0.78571429 -0.57142857 -0.35714286 -0.14285714  0.07142857
  0.28571429  0.5         0.71428571  0.92857143  1.14285714  1.35714286
  1.57142857  1.78571429  2.        ]


In [7]:
f = np.logspace(-1,2,15,endpoint=True,base =10)
print(f)# logspace  values of the above array  

[  0.1          0.16378937   0.26826958   0.43939706   0.71968567
   1.17876863   1.93069773   3.16227766   5.17947468   8.48342898
  13.89495494  22.75845926  37.2759372   61.05402297 100.        ]


In [8]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [9]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [17]:
g = np.fromfunction(lambda i,j:i==j,(4,5),dtype=int)
print(g)

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]]


# Array Operations

In [19]:
v = np.arange(18).reshape(3,6)
print(v)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [20]:
for i in v:
    print(2*i) 

[ 0  2  4  6  8 10]
[12 14 16 18 20 22]
[24 26 28 30 32 34]


In [23]:
v*3   #every element is multiplied by  2

array([[ 0,  3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30, 33],
       [36, 39, 42, 45, 48, 51]])

In [22]:
v+v  

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34]])

In [24]:
v*v

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289]])

In [25]:
print(v)
b = v.transpose()
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 0  6 12]
 [ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]]


In [26]:
v@b  #transpose and then multiply

array([[  55,  145,  235],
       [ 145,  451,  757],
       [ 235,  757, 1279]])

In [28]:
print(v)
v.sum(axis=1)    #sum along axis or the entire array                # if axis is 1 then suming along the column

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


array([15, 51, 87])

In [30]:
print(v)
v.sum(axis=0)    #sum along axis or the entire 
              # if axis is 0 then suming along the row

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


array([18, 21, 24, 27, 30, 33])

In [31]:
v.sum()  #sum of all the elements in the matrix

153

In [33]:
print(v.max(),v.min())   #gives max and the min value

17 0


# Universal Function

In [34]:
p =np.pi
print(p)

3.141592653589793


In [36]:
a= v*np.pi/12.0
print(a)

[[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694]
 [1.57079633 1.83259571 2.0943951  2.35619449 2.61799388 2.87979327]
 [3.14159265 3.40339204 3.66519143 3.92699082 4.1887902  4.45058959]]


In [38]:
l = np.tan(v)
print(l)

[[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01
   1.15782128e+00 -3.38051501e+00]
 [-2.91006191e-01  8.71447983e-01 -6.79971146e+00 -4.52315659e-01
   6.48360827e-01 -2.25950846e+02]
 [-6.35859929e-01  4.63021133e-01  7.24460662e+00 -8.55993401e-01
   3.00632242e-01  3.49391565e+00]]


# Array Slicing

#  x [START :END :STEP]

In [57]:
a  = np.arange(25)
print(a)
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
<class 'numpy.ndarray'>


In [58]:
even = a[0:24:2]
print(even)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [59]:
reverse = a[::-1]
print(reverse)

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1
  0]


In [64]:
reverse = a[::7]
print(reverse)

[ 0  7 14 21]


In [65]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# Multidimensional array

In [4]:
a= np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
a[4,2]

22

In [70]:
a[0:3,0:4]         #rows , column

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [5]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
a[:,2]      # all the elements in the second column
        #all rows and one column

array([ 2,  7, 12, 17, 22])

In [7]:
f =a.flatten()  #a multidimensional array is converted into a single dimensional array
print(f)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [9]:
for hello in f:
    print(hello)
b = np.arange(15).reshape(3,5)
print(b)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# Copying Arrays

In [10]:
a = np.arange(25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [13]:
b=a
print(b)
b is a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


True

In [14]:
b.shape=(5,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
a.shape    # a shape is also changed

(5, 5)

In [16]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [21]:
a= np.arange(10)
d =a[:]  #shallow copy
a.shape=(2,5)
print(a)
print("shallow",d)
a is d
# shallow creates  different files
 

[[0 1 2 3 4]
 [5 6 7 8 9]]
shallow [0 1 2 3 4 5 6 7 8 9]


False

In [25]:
d[2] = 63
print(a)
print(d)


[[ 0  1 63  3  4]
 [ 5  6  7  8  9]]
[ 0  1 63  3  4  5  6  7  8  9]


In [26]:
t = d[2:5]
print(t)

[63  3  4]


In [27]:
t[:] = 0

In [28]:
print(a)
print(d)
print(t)

[[0 1 0 0 0]
 [5 6 7 8 9]]
[0 1 0 0 0 5 6 7 8 9]
[0 0 0]


In [29]:
print(d is a)
print(d.base is a)  #data present at a is it same 
print(d.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [31]:
t = a.copy()
t[:,:] = 0.0
print(a)
print(t)

[[0 1 0 0 0]
 [5 6 7 8 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
