# Boolean Indexing

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
a[a>9]=0
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 0 0 0 0]]


In [4]:
a[a==0]=-1
print(a)

[[-1  1  2  3  4]
 [ 5  6  7  8  9]
 [-1 -1 -1 -1 -1]]


In [5]:
a==-1      #checks where -1 is present

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [7]:
a = np.arange(25).reshape(5,5)
print(a)
a[np.logical_and(a>5,a<=15)] = 0.0
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0 16 17 18 19]
 [20 21 22 23 24]]


In [9]:
a>6

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Avoiding Loops

In [ ]:
 M = 56
N=21
xmin = ymin =0.0
xmax= ymax=1.0
x= np.linspace(xmin,xmax,M,endpoint = False)
y= np.linspace(ymin,ymax,N,endpoint = False)
print(x.shape)
print(y.shape)
print(y)