In [1]:
import numpy as np


In [6]:
import time 
import numpy as np
A =45  #generate 45 points
B=25
xmin = ymin =0.0
xmax=ymax = 1.0

x= np.linspace(xmin,xmax,A,endpoint=True)
y= np.linspace(ymin,ymax,B,endpoint = True)
print(x)
print(y)

[0.         0.02272727 0.04545455 0.06818182 0.09090909 0.11363636
 0.13636364 0.15909091 0.18181818 0.20454545 0.22727273 0.25
 0.27272727 0.29545455 0.31818182 0.34090909 0.36363636 0.38636364
 0.40909091 0.43181818 0.45454545 0.47727273 0.5        0.52272727
 0.54545455 0.56818182 0.59090909 0.61363636 0.63636364 0.65909091
 0.68181818 0.70454545 0.72727273 0.75       0.77272727 0.79545455
 0.81818182 0.84090909 0.86363636 0.88636364 0.90909091 0.93181818
 0.95454545 0.97727273 1.        ]
[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]


In [11]:
t0=time.time()
g=np.zeros((A,B))
print(g)
for i in range(A):
    for j in range(B):
        g[i,j]=np.sin(2.0*np.pi*x[i]*y[j])
print(g)
t1=time.time()
print("Time elapsed :{}s".format(t1-t0))



[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.94995098e-03  1.18996913e-02 ...  1.30526192e-01
   1.36422930e-01  1.42314838e-01]
 [ 0.00000000e+00  1.18996913e-02  2.37976975e-02 ...  2.58819045e-01
   2.70294939e-01  2.81732557e-01]
 ...
 [ 0.00000000e+00  2.47306501e-01  4.79248987e-01 ... -7.07106781e-01
  -5.10270033e-01 -2.81732557e-01]
 [ 0.00000000e+00  2.53067252e-01  4.89659163e-01 ... -6.08761429e-01
  -3.88173696e-01 -1.42314838e-01]
 [ 0.00000000e+00  2.58819045e-01  5.00000000e-01 ... -5.00000000e-01
  -2.58819045e-01 -2.44929360e-16]]
Time elapsed :0.00821995735168457s


In [12]:
x2d,y2d = np.meshgrid(x,y,indexing="ij")
print(x2d[:,0])
print(x2d[0,:])

[0.         0.02272727 0.04545455 0.06818182 0.09090909 0.11363636
 0.13636364 0.15909091 0.18181818 0.20454545 0.22727273 0.25
 0.27272727 0.29545455 0.31818182 0.34090909 0.36363636 0.38636364
 0.40909091 0.43181818 0.45454545 0.47727273 0.5        0.52272727
 0.54545455 0.56818182 0.59090909 0.61363636 0.63636364 0.65909091
 0.68181818 0.70454545 0.72727273 0.75       0.77272727 0.79545455
 0.81818182 0.84090909 0.86363636 0.88636364 0.90909091 0.93181818
 0.95454545 0.97727273 1.        ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [15]:
print(y2d[:,0])
print(y2d[0,:])



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]


In [16]:
print(x2d)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.02272727 0.02272727 0.02272727 ... 0.02272727 0.02272727 0.02272727]
 [0.04545455 0.04545455 0.04545455 ... 0.04545455 0.04545455 0.04545455]
 ...
 [0.95454545 0.95454545 0.95454545 ... 0.95454545 0.95454545 0.95454545]
 [0.97727273 0.97727273 0.97727273 ... 0.97727273 0.97727273 0.97727273]
 [1.         1.         1.         ... 1.         1.         1.        ]]


In [19]:
jk = [1,0,2,3,4,5]
result = int(all(jk))
print(result)

0


# Numpy Standard data types

In [36]:
a= np.zeros(10,dtype ='int8')
print(a.dtype)
print(a)

int8
[0 0 0 0 0 0 0 0 0 0]


In [40]:
b= np.zeros(20,dtype='float64')
print(b.dtype)
print(b)

float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [41]:
b= np.zeros(20,dtype='int64')
print(b.dtype)
print(b)

int64
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


# Array concantenation  and splitting

In [50]:
x = np.array([1,2,3,4])
y=np.array([7,8,9,5])
t= np.concatenate([x,y])
print([x,y])
print([t])
q = t.reshape(4,2)
t.reshape(2,4)
#print(q)

[array([1, 2, 3, 4]), array([7, 8, 9, 5])]
[array([1, 2, 3, 4, 7, 8, 9, 5])]
[[1 2]
 [3 4]
 [7 8]
 [9 5]]


In [53]:
grid  = np.array([[78,89,45,],[12,23,25]])
print(grid)

[[78 89 45]
 [12 23 25]]


In [55]:
#based on rows
np.concatenate([grid,grid]) #concatenate along the first axis

array([[78, 89, 45],
       [12, 23, 25],
       [78, 89, 45],
       [12, 23, 25]])

In [57]:
#based on the columns
np.concatenate([grid,grid],axis = 1) #concatenate along the second axis

array([[78, 89, 45, 78, 89, 45],
       [12, 23, 25, 12, 23, 25]])

# Splitting of the arrays

In [75]:
l=[1,2,31,46,64,34,84,333,764,3]
len(l)

10

In [77]:
c1,c2,c3,c4 = np.split(l,[2,4,6])
print(c1,c2,c3,c4)

[1 2] [31 46] [64 34] [ 84 333 764   3]


In [79]:
asd= np.arange(27).reshape(3,9)
print(asd)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


In [81]:
left,right = np.hsplit(asd,[5]) #spliited based on the index postion
print(left)
print(right)

[[ 0  1  2  3  4]
 [ 9 10 11 12 13]
 [18 19 20 21 22]]
[[ 5  6  7  8]
 [14 15 16 17]
 [23 24 25 26]]


In [82]:
left,right = np.vsplit(asd,[5]) #spliited based on the index postion
print(left)
print(right)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]
[]


# Aggregates

In [91]:
w = np.arange(1,15)
print(w)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [92]:
np.add.reduce(w)

105

In [93]:
np.multiply.reduce(w)

87178291200

In [96]:
print(w)
np.add.accumulate(w)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105])

In [101]:
print(w)
np.multiply.accumulate(w)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([          1,           2,           6,          24,         120,
               720,        5040,       40320,      362880,     3628800,
          39916800,   479001600,  6227020800, 87178291200])